DROP TABLE Customer;
DROP TABLE Product;
DROP TABLE [Order];

CREATE TABLE Customer (
	Id			INT PRIMARY KEY IDENTITY NOT NULL,
	[Name]		NVARCHAR(200) NOT NULL,
	Adress		NVARCHAR(200) NOT NULL,
	ZipCode		NVARCHAR(5) NOT NULL,
	City		NVARCHAR(100) NOT NULL
)

CREATE TABLE Product (
	Id			INT PRIMARY KEY IDENTITY NOT NULL,
	[Name]		NVARCHAR(100) NOT NULL,
	Price		INT NOT NULL,
	Quantity	INT NOT NULL,
)

CREATE TABLE [Order] (
	Id				INT PRIMARY KEY IDENTITY NOT NULL,
	CustomerId		INT FOREIGN KEY REFERENCES Customer(Id) NOT NULL,
	OrderDate		DATETIME NOT NULL,
	TotalPrice		INT NOT NULL,
	Billed			BIT NOT NULL,
	BilledDate		DATETIME,
	[Sent]			BIT NOT NULL,
	SentDate		DATETIME,
)

CREATE TABLE OrderProduct (
	OrderId			INT FOREIGN KEY REFERENCES [Order](Id) NOT NULL,
	ProductId		INT FOREIGN KEY REFERENCES Product(Id) NOT NULL, 
)

ALTER TABLE OrderProduct
ADD CONSTRAINT PK_OrdPro
PRIMARY KEY (OrderId, ProductId)